### PR TITLE
adjust events to support OTX2.3.x -  Fix #43

### LINKED ISSUE #43: OpenTX 2.3.4 compability issues
On OpenTX 2.3.4 LUA script can't save any parameters besides D Setpoint value. Same script on OpenTX 2.2.* works fine.

### PR DESCRIPTION
**Pull request by lichtl**
- Fix for opentx 2.3.x (usage of virtual events) - https://github.com/flyduino/kissfc-tx-lua-scripts/issues/43
- Cleanup (Xlite should be no longer needed)

Untested

### CODE REVIEW

**Comment by lichtl** [comment]
X9D - HW test OK
Xlite - SIM test OK
Horus - SIM test OK

[kiss-128x64-lua-scripts-1.0.0.zip](https://github.com/flyduino/kissfc-tx-lua-scripts/files/4012251/kiss-128x64-lua-scripts-1.0.0.zip)
[kiss-212x64-lua-scripts-1.0.0.zip](https://github.com/flyduino/kissfc-tx-lua-scripts/files/4012252/kiss-212x64-lua-scripts-1.0.0.zip)
[kiss-480x272-lua-scripts-1.0.0.zip](https://github.com/flyduino/kissfc-tx-lua-scripts/files/4012253/kiss-480x272-lua-scripts-1.0.0.zip)

**Comment by syrekszymon** [comment]
X9D kiss-212x64-lua-scripts-1.0.0.zip

PIDs - don't save
Rates - don't save
TPA - don't save
Filters - don't save
Aalrms - save 
VTX - save
D setpoint - save

**Comment by lichtl** [comment]
> X9D kiss-212x64-lua-scripts-1.0.0.zip
> 
> PIDs - don't save
> Rates - don't save
> TPA - don't save
> Filters - don't save
> Aalrms - save
> VTX - save
> D setpoint - save

Hmm I've tested on X9D+ and PIDs/Rates worked. Since all use the same function (which haven't changed) it should work. Will test later again on hardware but please ensure there is enough distance between transmitter and quad.

**Comment by AngusCox** [comment]
Same thing happens with X7, using kiss-128x64-lua-scripts-1.0.0.zip (KissCF.lua). Open TX 2.3.2
PIDs - don't save
Rates - don't save
TPA - don't save
Filters - don't save
Alarms - save
VTX - save
D setpoint - save

**Comment by lichtl** [comment]
yes confirmed. on T16 it also cause to go into emergency mode. I currently still try to find out what causes this since function wise all pages share the same generic code to send. I probably have to raise an issue at opentx.

**Comment by lichtl** [comment]
it also seems to be related to crossfire. Frsky SPORT PID change works fine on X9D

**Comment by AngusCox** [comment]
> it also seems to be related to crossfire. Frsky SPORT PID change works fine on X9D

Let me know when you have something to test

**Comment by fedorcomander** [comment]
https://youtu.be/EgBP70yGE-o <https://youtu.be/EgBP70yGE-o>

Just retested.

40o
NOT latest LUA (my last committed one, i think 0.11 or .12?
OpenTX 2.2.0

**Comment by AngusCox** [comment]
I'm trying to add more information for the understanding of the problem.
Talking with @fedorcomander about this issue, and explaining to him that Alarms, VTX and Setpoints Tabs work fine, he told me the following about the difference between them and the other TABs:

"amount of data. pid packet is splitted. vtx - not and if u SEE pids... means FC cuts data to chunks fine... and on the way back - something or wrong with lua or opentx"
"also, crossfire lua uses special crossfire commands TBS made for me, but they should be ok because its TBS stuff."

**Comment by lichtl** [comment]
Hi. did some further looking into it. BF seems to use same CF functionallity. I try to find out later if it is the size. But it looks like there is something with the crossfireTelemetryPush funtion

**Comment by awolf78** [comment]
@AngusCox What CRSF version are you running?

**Comment by AngusCox** [comment]
> @AngusCox What CRSF version are you running?

@awolf78 CRSF 3.23 on both, TX and RX.

**Comment by lichtl** [comment]
I have same issue on 3.24 and going back to 2.2x it is working. Will hopefully have some more time later to get more idea about the exact root cause in opentx

**Comment by AngusCox** [comment]
> I have same issue on 3.24 and going back to 2.2x it is working. Will hopefully have some more time later to get more idea about the exact root cause in opentx

@ thanks for the update!

**Comment by lichtl** [comment]
Ok did some further testing yesterday. This is opentx related and apply to opentx 2.3.x. I've just raised an issue.

https://github.com/opentx/opentx/issues/7310

**Comment by lichtl** [comment]
opentx fix is in latest nightly. Will test this today.

**Comment by AngusCox** [comment]
I will also try to test it on X7

**Comment by lichtl** [comment]
tested on T16 and X9D+ with current nightly N116. All pages do save.
Here is the latest version if someone want to test 

[kiss-128x64-lua-scripts-1.0.0.zip](https://github.com/flyduino/kissfc-tx-lua-scripts/files/4142361/kiss-128x64-lua-scripts-1.0.0.zip)
[kiss-212x64-lua-scripts-1.0.0.zip](https://github.com/flyduino/kissfc-tx-lua-scripts/files/4142362/kiss-212x64-lua-scripts-1.0.0.zip)
[kiss-480x272-lua-scripts-1.0.0.zip](https://github.com/flyduino/kissfc-tx-lua-scripts/files/4142363/kiss-480x272-lua-scripts-1.0.0.zip)

**Comment by AngusCox** [comment]
> tested on T16 and X9D+ with current nightly N116. All pages do save. (N116 SD also include the crossfire lua fix from Alex)
> Here is the latest version if someone want to test
> 
> [kiss-128x64-lua-scripts-1.0.0.zip](https://github.com/flyduino/kissfc-tx-lua-scripts/files/4142361/kiss-128x64-lua-scripts-1.0.0.zip)
> [kiss-212x64-lua-scripts-1.0.0.zip](https://github.com/flyduino/kissfc-tx-lua-scripts/files/4142362/kiss-212x64-lua-scripts-1.0.0.zip)
> [kiss-480x272-lua-scripts-1.0.0.zip](https://github.com/flyduino/kissfc-tx-lua-scripts/files/4142363/kiss-480x272-lua-scripts-1.0.0.zip)

Tested on X7 with current nightly N116 (02-01). All pages work perfectly.
Excellent work!

**Pull request merged**
